[project]
name = "market-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.1",
    "lxml>=6.0.0",
    "pytesseract>=0.3.13",
    "selenium>=4.34.0",
    "webdriver-manager>=4.0.2",
]
